require 'bundler/setup'
require 'yaml'
require 'oauth'
require 'base64'
require 'uri'
require "#{File.dirname(__FILE__)}/f1api/configuration"
require "#{File.dirname(__FILE__)}/f1api/oauth"
require "#{File.dirname(__FILE__)}/f1api/oauth/credentials_authentication"
require "#{File.dirname(__FILE__)}/f1api/oauth/oauth_authentication"
require "#{File.dirname(__FILE__)}/f1api/client"
require "#{File.dirname(__FILE__)}/f1api/base"